name: CI/CD for Docker App

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t my-docker-app .

    - name: Run Docker container
      run: docker run -d -p 5000:5000 --name my-docker-container my-docker-app
